### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by KunSu** [zijianguan0204/HungerAtHome_backend#1]
**1. user/getUserID should be a GET method**
The rest of them should change to the corresponding method accordingly
![image](https://user-images.githubusercontent.com/55034108/98427985-53311780-2054-11eb-88a8-b7c3338d4a01.png)

**2. The email and password should use payload instead of Parameters**
![image](https://user-images.githubusercontent.com/55034108/98428129-e702e380-2054-11eb-895a-a4acb833901b.png)

And the Response body should return a User like this
{
  "companyID": "string",
  "email": "string",
  "firstName": "string",
  "id": "string",
  "lastName": "string",
  "phoneNumber": "string",
  "status": "string",
  "userIdentity": "string"
}

**3. Change the user/signup/ Responses to** 
{
  "companyID": "string",
  "email": "string",
  "firstName": "string",
  "id": "string",
  "lastName": "string",
  "phoneNumber": "string",
  "status": "string",
  "userIdentity": "string"
}

**4. For all enum types of input/output, you might want to add them into the swagger to avoid confusion.** 
userIdentity: a, b, c

**5. For all APIs**
You need to handle basic errors
For example: /user/login/
input:
![image](https://user-images.githubusercontent.com/55034108/98428337-e3239100-2055-11eb-9eb8-bc49dd969884.png)
API output:
![image](https://user-images.githubusercontent.com/55034108/98428344-e9197200-2055-11eb-8ba9-00460a54dcc1.png)
You should return an error message instead.

**6. You can not assume all input is valid.**

**7. API bug. You need basic API testing on local. Functional testing**
input:
![image](https://user-images.githubusercontent.com/55034108/98428441-5b8a5200-2056-11eb-9577-6c9dd6e21895.png)
output:
"message": "This email address is already taken"
![image](https://user-images.githubusercontent.com/55034108/98428465-6d6bf500-2056-11eb-880d-3681b75fcf88.png)

**8. Logic bug**
You did not check if companyID exists or not for creating a new user.
You did not check if userIdentity matches your enum type or not.
The password should be encoded one more time.

**9. HTTP Code bug**
/user/signup/
![image](https://user-images.githubusercontent.com/55034108/98428574-03078480-2057-11eb-8841-7b7e738d2d98.png)

Server error should be 400 level like 400 Bad Request
Use 500 only when the server down or crash.

**Comment by zijianguan0204** [comment]
1. Fixed the get api with proper methods
2. Changed from Get to Post in order to pass by payload
3. Already did
4. Need frontend passing a userID for backend user identity verification
5. Fixed partially, more apis are being tested along the way

TODO:
Http code verification
userIdentity verification
identity input check when signup
